import { SalesRecord, DayData } from '../types';

export const SAMPLE_RAW: SalesRecord[] = [
  {
    plant: "INFA",
    customer: "ENDRESS+HAUSER FLOWTEC (INDIA) PRIVATE LIMITED",
    segment: "General Engineering",
    invoiceType: "Domestic Invoice",
    salesLacs: 0.9446,
    quantity: 34,
    onTime: 1,
    failure: 0,
    productType: "Produ",
    orderType: "PO",
    billingDate: "2026-04-07",
    material: "Housing G335 MODBUS MACH.",
    accountManager: "Rajesh Kumar"
  },
  {
    plant: "INFA",
    customer: "HI TECH ARAI PRIVATE LIMITED",
    segment: "",
    invoiceType: "Domestic Invoice",
    salesLacs: 0.2132,
    quantity: 164,
    onTime: 0,
    failure: 0,
    productType: "NPD",
    orderType: "PO",
    billingDate: "2026-04-08",
    material: "Inlet Transition Piece",
    accountManager: "Amit Shah"
  },
  {
    plant: "INFA",
    customer: "HI TECH ARAI PRIVATE LIMITED",
    segment: "",
    invoiceType: "Domestic Invoice",
    salesLacs: 0.0845,
    quantity: 65,
    onTime: 0,
    failure: 0,
    productType: "NPD",
    orderType: "PO",
    billingDate: "2026-04-08",
    material: "Inlet Transition Piece",
    accountManager: "Amit Shah"
  },
  {
    plant: "INFA",
    customer: "HI TECH ARAI PRIVATE LIMITED",
    segment: "",
    invoiceType: "Domestic Invoice",
    salesLacs: 0.0286,
    quantity: 22,
    onTime: 0,
    failure: 0,
    productType: "NPD",
    orderType: "PO",
    billingDate: "2026-04-08",
    material: "Inlet Transition Piece",
    accountManager: "Amit Shah"
  },
  {
    plant: "INFA",
    customer: "NR INDUSTRIES",
    segment: "Automotive",
    invoiceType: "Domestic Invoice",
    salesLacs: 0.2921,
    quantity: 72,
    onTime: 1,
    failure: 0,
    productType: "Produ",
    orderType: "SCH",
    billingDate: "2026-04-08",
    material: "HINGE ASM- BODY SIDE",
    accountManager: "Rajesh Kumar"
  },
  {
    plant: "INFA",
    customer: "NR INDUSTRIES",
    segment: "Automotive",
    invoiceType: "Domestic Invoice",
    salesLacs: 0.2906,
    quantity: 104,
    onTime: 1,
    failure: 0,
    productType: "Produ",
    orderType: "SCH",
    billingDate: "2026-04-08",
    material: "HINGE DOOR SIDE",
    accountManager: "Rajesh Kumar"
  },
  {
    plant: "INFA",
    customer: "SUHAS ENTERPRISES",
    segment: "Automotive",
    invoiceType: "Domestic Invoice",
    salesLacs: 0.2936,
    quantity: 153,
    onTime: 0,
    failure: 0,
    productType: "Produ",
    orderType: "SCH",
    billingDate: "2026-04-08",
    material: "SHIFTER FORK (3RD/4TH)",
    accountManager: "Suresh Prabhu"
  },
  {
    plant: "INFA",
    customer: "TML COMMERCIAL VEHICLES LIMITED",
    segment: "",
    invoiceType: "Domestic Invoice",
    salesLacs: 0.0281,
    quantity: 10,
    onTime: 1,
    failure: 0,
    productType: "Produ",
    orderType: "SCH",
    billingDate: "2026-04-08",
    material: "Shifter Dog 5th/6th/Rev.",
    accountManager: "Amit Shah"
  },
  {
    plant: "INFA",
    customer: "ENDRESS+HAUSER FLOWTEC (INDIA) PRIVATE LIMITED",
    segment: "General Engineering",
    invoiceType: "Domestic Invoice",
    salesLacs: 1.6121,
    quantity: 100,
    onTime: 1,
    failure: 0,
    productType: "Produ",
    orderType: "PO",
    billingDate: "2026-04-09",
    material: "Hous supp 200PW HT CF3M mach",
    accountManager: "Rajesh Kumar"
  },
  {
    plant: "INFB",
    customer: "TML COMMERCIAL VEHICLES LIMITED",
    segment: "",
    invoiceType: "Domestic Invoice",
    salesLacs: 0.299,
    quantity: 480,
    onTime: 1,
    failure: 0,
    productType: "Produ",
    orderType: "PO",
    billingDate: "2026-04-08",
    material: "Assy. P.C.Chamber with Ball",
    accountManager: "Suresh Prabhu"
  },
  {
    plant: "INFB",
    customer: "NR INDUSTRIES",
    segment: "Automotive",
    invoiceType: "Domestic Invoice",
    salesLacs: 0.3182,
    quantity: 140,
    onTime: 0,
    failure: 0,
    productType: "Produ",
    orderType: "SCH",
    billingDate: "2026-04-13",
    material: "HINGELEAF BODYSIDE281672303701",
    accountManager: "Rajesh Kumar"
  }
  // Simplified for example, actual mapping from HTML array below in application
];

export const SAMPLE_DAYS_RAW: DayData[] = [
  {"d":"07-Apr","infa":0.945,"infb":0.0},
  {"d":"08-Apr","infa":4.898,"infb":0.299},
  {"d":"09-Apr","infa":1.612,"infb":5.356},
  {"d":"10-Apr","infa":4.742,"infb":0.0},
  {"d":"13-Apr","infa":25.907,"infb":6.758},
  {"d":"14-Apr","infa":18.903,"infb":0.0},
  {"d":"15-Apr","infa":0.0,"infb":1.814},
  {"d":"16-Apr","infa":30.131,"infb":7.374},
  {"d":"17-Apr","infa":22.466,"infb":11.085},
  {"d":"18-Apr","infa":1.121,"infb":0.0},
  {"d":"19-Apr","infa":30.904,"infb":0.0},
  {"d":"20-Apr","infa":23.147,"infb":9.96},
  {"d":"21-Apr","infa":22.298,"infb":6.952},
  {"d":"22-Apr","infa":15.15,"infb":11.876},
  {"d":"23-Apr","infa":35.342,"infb":18.637},
  {"d":"24-Apr","infa":49.709,"infb":2.888},
  {"d":"25-Apr","infa":0.727,"infb":24.358}
];
